trigger:
- main   # or whichever branch you want to trigger on

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  enabled: true
  displayName: "Install dependencies"
  inputs:
    targetType: 'inline'
    script: 'npm ci'
    workingDirectory: tests # update accordingly

- task: AzureCLI@2
  displayName: Run Playwright Test  
  env:
    PLAYWRIGHT_SERVICE_URL: $(PLAYWRIGHT_SERVICE_URL)
    # PLAYWRIGHT_SERVICE_ACCESS_TOKEN: $(PLAYWRIGHT_SERVICE_ACCESS_TOKEN) # Not recommended, use Microsoft Entra ID authentication. 

  inputs:
    azureSubscription: SRJ # Service connection used to authenticate this pipeline with Azure to use the service
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      npx playwright test -c playwright.service.config.ts --workers=20
  addSpnToEnvironment: true

- task: PublishPipelineArtifact@1
  displayName: Upload Playwright report
  inputs:
    targetPath: E2ECart\playwright-report # update accordingly
    artifact: 'Playwright tests'
    publishLocation: 'pipeline'